# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MediaWiki-API
version:      0.07
version_from: lib/MediaWiki/API.pm
installdirs:  site
requires:
    JSON::XS:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
