--- #YAML:1.0
name:                MediaWiki-API
version:             0.20
abstract:            Provides a Perl interface to the MediaWiki API (http://www.mediawiki.org/wiki/API)
license:             ~
author:              
    - Jools Smyth <buzz@exotica.org.uk>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Encode:                        0
    JSON::XS:                      0
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
